# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MAIN(QtWidgets.QWidget):

    def __init__(self):
        QtWidgets.QWidget.__init__(self)
        self.setupUi(self)

    def setupUi(self, MAIN):
        MAIN.setObjectName("MAIN")
        MAIN.resize(982, 493)
        MAIN.setStyleSheet("background:white;")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(MAIN)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(20, 10, 951, 479))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.receiverName = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.receiverName.setObjectName("receiverName")
        self.verticalLayout.addWidget(self.receiverName)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.receiverMail = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.receiverMail.setObjectName("receiverMail")
        self.verticalLayout.addWidget(self.receiverMail)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.receiverInfo = QtWidgets.QTextEdit(self.verticalLayoutWidget_7)
        self.receiverInfo.setObjectName("receiverInfo")
        self.verticalLayout.addWidget(self.receiverInfo)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_7)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget_7)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(20, 22, 421, 307))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.senderName = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.senderName.setObjectName("senderName")
        self.verticalLayout_6.addWidget(self.senderName)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.senderMail = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.senderMail.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.senderMail.setObjectName("senderMail")
        self.verticalLayout_6.addWidget(self.senderMail)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.senderPass = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.senderPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.senderPass.setObjectName("senderPass")
        self.verticalLayout_6.addWidget(self.senderPass)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_6.addWidget(self.label_17)
        self.senderPhone = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.senderPhone.setEchoMode(QtWidgets.QLineEdit.Password)
        self.senderPhone.setObjectName("senderPhone")
        self.verticalLayout_6.addWidget(self.senderPhone)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14)
        self.senderSchool = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.senderSchool.setEchoMode(QtWidgets.QLineEdit.Password)
        self.senderSchool.setObjectName("senderSchool")
        self.verticalLayout_6.addWidget(self.senderSchool)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_6.addWidget(self.label_15)
        self.senderDiv = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.senderDiv.setEchoMode(QtWidgets.QLineEdit.Password)
        self.senderDiv.setObjectName("senderDiv")
        self.verticalLayout_6.addWidget(self.senderDiv)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 20, 431, 321))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_8.addWidget(self.label_12)
        self.appPosition = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.appPosition.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.appPosition.setObjectName("appPosition")
        self.verticalLayout_8.addWidget(self.appPosition)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_8.addWidget(self.label_13)
        self.senderSkills = QtWidgets.QTextEdit(self.verticalLayoutWidget_8)
        self.senderSkills.setObjectName("senderSkills")
        self.verticalLayout_8.addWidget(self.senderSkills)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_8.addWidget(self.label_16)
        self.senderMore = QtWidgets.QTextEdit(self.verticalLayoutWidget_8)
        self.senderMore.setObjectName("senderMore")
        self.verticalLayout_8.addWidget(self.senderMore)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.mailSubject = QtWidgets.QLineEdit(self.tab_5)
        self.mailSubject.setGeometry(QtCore.QRect(10, 30, 431, 22))
        self.mailSubject.setObjectName("mailSubject")
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 391, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 391, 16))
        self.label_5.setObjectName("label_5")
        self.mailMessage = QtWidgets.QTextEdit(self.tab_5)
        self.mailMessage.setGeometry(QtCore.QRect(10, 80, 431, 281))
        self.mailMessage.setObjectName("mailMessage")
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.appButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.appButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.appButton.setFont(font)
        self.appButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.appButton.setStyleSheet("background: #3bb865;\n"
"color:white;\n"
"border-radius:15px;")
        self.appButton.setObjectName("appButton")
        self.verticalLayout_7.addWidget(self.appButton)

        self.retranslateUi(MAIN)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MAIN)

    def retranslateUi(self, MAIN):
        _translate = QtCore.QCoreApplication.translate
        MAIN.setWindowTitle(_translate("MAIN", "Lori"))
        self.label_7.setText(_translate("MAIN", "Başvuru yapılacak yer"))
        self.label.setText(_translate("MAIN", "Şirket/kişi adı"))
        self.label_2.setText(_translate("MAIN", "Şirket/kişi mail adresi"))
        self.label_3.setText(_translate("MAIN", "Şirket/kişi bilgileri"))
        self.label_8.setText(_translate("MAIN", "Başvuru yapacak kişi"))
        self.label_9.setText(_translate("MAIN", "Kişi isim soyisim"))
        self.label_10.setText(_translate("MAIN", "Kişi mail adresi"))
        self.label_11.setText(_translate("MAIN", "Kişi mail şifresi"))
        self.label_17.setText(_translate("MAIN", "Kişi telefon numarası"))
        self.label_14.setText(_translate("MAIN", "Okul"))
        self.label_15.setText(_translate("MAIN", "Bölüm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MAIN", "Kişi bilgileri"))
        self.label_12.setText(_translate("MAIN", "Başvuru pozisyonu"))
        self.label_13.setText(_translate("MAIN", "Kişi yetkinlikleri (virgülle ayırın)"))
        self.label_16.setText(_translate("MAIN", "Ek bilgiler (varsa)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MAIN", "Başvuru bilgileri"))
        self.label_4.setText(_translate("MAIN", "Mail başlığı"))
        self.label_5.setText(_translate("MAIN", "Mail yazısı"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MAIN", "Mail içeriği"))
        self.appButton.setText(_translate("MAIN", "Başvuru oluştur!"))

class Ui_FILES(QtWidgets.QWidget):

    def __init__(self):
        QtWidgets.QWidget.__init__(self)
        self.setupUi(self)
        
    def setupUi(self, FILES):
        FILES.setObjectName("FILES")
        FILES.resize(502, 515)
        self.listWidget = QtWidgets.QListWidget(FILES)
        self.listWidget.setGeometry(QtCore.QRect(20, 50, 461, 331))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.listWidget.setFont(font)
        self.listWidget.setProperty("isWrapping", False)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/mail.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/cv.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/pdf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listWidget.addItem(item)
        self.label_4 = QtWidgets.QLabel(FILES)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(FILES)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 390, 461, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton.setStyleSheet("background: #3bb865;\n"
"color:white;\n"
"border-radius:15px;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_2.setStyleSheet("background: orange;\n"
"color:white;\n"
"border-radius:15px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)

        self.retranslateUi(FILES)
        QtCore.QMetaObject.connectSlotsByName(FILES)

    def retranslateUi(self, FILES):
        _translate = QtCore.QCoreApplication.translate
        FILES.setWindowTitle(_translate("FILES", "Files"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("FILES", "Mail içeriği"))
        item = self.listWidget.item(1)
        item.setText(_translate("FILES", "Özgeçmiş"))
        item = self.listWidget.item(2)
        item.setText(_translate("FILES", "Başvuru mektubu.pdf"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("FILES", "Hazırlanan belgeler"))
        self.pushButton.setText(_translate("FILES", "Onayla!"))
        self.pushButton_2.setText(_translate("FILES", "Düzenle!"))
        self.pushButton_3.setText(_translate("FILES", "Geri"))